### ISSUE TITLE
Doesnt Work with Floating Code Editor

### ISSUE THREAD

**Issue by brwxisme** [Herbherth/GDScript-Quality-of-Life#2]
It was working once or twice on Floating mode, but then it doesnt.
And i cant reproduce how to make it work on Floating mode.
No problem at all on docked window.

Godot 4.2.2-stable
Nixos

cool plugin, love it

**Comment by brwxisme** [comment]
update, how to reproduce
> Click on 2D editor
> Script Editor
> Make it Floating
> It Works
 problem starts here, if u click any of 2D, 3D, Asset Lib, it will Stop Working again

**Comment by Herbherth** [comment]
Hi, thank you for the comments :D, yeah, I tested it here and already noticed what the problem is. Godot is not calling [Viewport.gui_focus_changed](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-signal-gui-focus-changed) when floating. I am going to check if there is another way to do it

**Comment by brwxisme** [comment]
fixed in this link below:
but, there is a downside on my version, it need to be focused once before using/ make it floating window


https://github.com/brwxisme/GDScript-Quality-of-Life

**Comment by Herbherth** [comment]
> fixed in this link below: but, there is a downside on my version, it need to be focused once before using/ make it floating window
> 
> https://github.com/brwxisme/GDScript-Quality-of-Life

Oh, thank you, but I was also making it work, hahah, I think my solution is simplier and works better (no need to use it before floating.

Updated it ;)

**Comment by brwxisme** [comment]
Nice!
